import 'package:hive/hive.dart';

enum TransactionSource {
  manual,
  pdfImport,

  /// Auto-generated by [RecurringTransactionService] as the next occurrence
  /// of a booking flagged as recurring (isRecurring). Appended at the end
  /// so existing persisted indices (manual=0, pdfImport=1) stay stable.
  recurringGenerated,
}

class TransactionSourceAdapter extends TypeAdapter<TransactionSource> {
  @override
  final int typeId = 4;

  @override
  TransactionSource read(BinaryReader reader) => TransactionSource.values[reader.readByte()];

  @override
  void write(BinaryWriter writer, TransactionSource obj) => writer.writeByte(obj.index);
}

/// A single booked amount on an account. Positive [amount] is income,
/// negative [amount] is an expense.
class Transaction extends HiveObject {
  Transaction({
    required this.id,
    required this.date,
    required this.amount,
    required this.description,
    required this.categoryId,
    this.subcategoryId,
    this.source = TransactionSource.manual,
    this.isRecurring = false,
    this.personId,
    this.accountId,
    this.isTransfer = false,
    this.transferGroupId,
  });

  final String id;
  DateTime date;
  double amount;
  String description;
  String categoryId;
  String? subcategoryId;
  TransactionSource source;
  bool isRecurring;

  /// Household member this booking is attributed to. `null` means
  /// "Gemeinsam" (shared, not attributed to one person).
  String? personId;

  /// Which [Account] this booking affects. `null` means it isn't tracked
  /// against a specific account (the app worked without accounts before
  /// this field existed, so this stays optional).
  String? accountId;

  /// True for one half of an internal transfer between two of the user's
  /// own accounts. Excluded from income/expense totals, budgets and
  /// optimization insights - it doesn't represent real income or spending -
  /// but still counts towards the affected accounts' balances.
  bool isTransfer;

  /// Links the two [Transaction]s that make up one transfer (the debit from
  /// the source account and the credit to the destination account), so they
  /// can be deleted together.
  String? transferGroupId;

  bool get isIncome => amount >= 0;

  Map<String, dynamic> toJson() => {
        'id': id,
        'date': date.millisecondsSinceEpoch,
        'amount': amount,
        'description': description,
        'categoryId': categoryId,
        'subcategoryId': subcategoryId,
        'source': source.index,
        'isRecurring': isRecurring,
        'personId': personId,
        'accountId': accountId,
        'isTransfer': isTransfer,
        'transferGroupId': transferGroupId,
      };

  static Transaction fromJson(Map<String, dynamic> json) => Transaction(
        id: json['id'] as String,
        date: DateTime.fromMillisecondsSinceEpoch(json['date'] as int),
        amount: (json['amount'] as num).toDouble(),
        description: json['description'] as String,
        categoryId: json['categoryId'] as String,
        subcategoryId: json['subcategoryId'] as String?,
        source: TransactionSource.values[json['source'] as int],
        isRecurring: json['isRecurring'] as bool,
        personId: json['personId'] as String?,
        accountId: json['accountId'] as String?,
        isTransfer: json['isTransfer'] as bool? ?? false,
        transferGroupId: json['transferGroupId'] as String?,
      );
}

class TransactionAdapter extends TypeAdapter<Transaction> {
  @override
  final int typeId = 2;

  @override
  Transaction read(BinaryReader reader) {
    final map = reader.readMap();
    return Transaction(
      id: map['id'] as String,
      date: DateTime.fromMillisecondsSinceEpoch(map['date'] as int),
      amount: map['amount'] as double,
      description: map['description'] as String,
      categoryId: map['categoryId'] as String,
      subcategoryId: map['subcategoryId'] as String?,
      source: TransactionSource.values[map['source'] as int],
      isRecurring: map['isRecurring'] as bool,
      personId: map['personId'] as String?,
      accountId: map['accountId'] as String?,
      isTransfer: map['isTransfer'] as bool? ?? false,
      transferGroupId: map['transferGroupId'] as String?,
    );
  }

  @override
  void write(BinaryWriter writer, Transaction obj) {
    writer.writeMap({
      'id': obj.id,
      'date': obj.date.millisecondsSinceEpoch,
      'amount': obj.amount,
      'description': obj.description,
      'categoryId': obj.categoryId,
      'subcategoryId': obj.subcategoryId,
      'source': obj.source.index,
      'isRecurring': obj.isRecurring,
      'personId': obj.personId,
      'accountId': obj.accountId,
      'isTransfer': obj.isTransfer,
      'transferGroupId': obj.transferGroupId,
    });
  }
}
